[server]
bind_addr = "0.0.0.0:53"
api_port = 5380
# api_bind_addr = "127.0.0.1"
data_dir = "#FLYENV_DATA_DIR#"

[upstream]
mode = "forward"
address = ["9.9.9.9", "1.1.1.1"]
fallback = ["8.8.8.8"]
timeout_ms = 3000

[blocking]
enabled = true
refresh_hours = 24
lists = ["https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/pro.txt"]

[cache]
max_entries = 100000
min_ttl = 60
max_ttl = 86400

[proxy]
enabled = true
port = 80
tls_port = 443
tld = "numa"
bind_addr = "127.0.0.1"

[mobile]
enabled = true
